### ISSUE TITLE
Not Verified on eCloud

### ISSUE THREAD

**Issue by TypicalModMaker** [Toshimichi0915/fetch#2]
Hey,
Could you get your extension verified on eCloud? [https://api.extendedclip.com/expansions/fetch/](https://api.extendedclip.com/expansions/fetch/)

Would be helpful for many people
Thanks!

**Comment by Toshimichi0915** [comment]
![image](https://user-images.githubusercontent.com/26406334/223691799-2e2b8776-b57f-48c6-b6c8-ccda6df59ad6.png)
