### ISSUE TITLE
use UTF8

### ISSUE THREAD

**Issue by QWXL** [Toshimichi0915/fetch#4]
I hope your extension can support using UTF-8 encoding to fetch url content. I mean, both fetching and receiving information using UTF-8, otherwise, when I use non-ISO characters as part of the url, the problem arises

**Comment by Toshimichi0915** [comment]
I think you can just encode your url?

https://www.urlencoder.org/

**Comment by QWXL** [comment]
> I think you can just encode your url?
> 
> https://www.urlencoder.org/

In my server, fetch is automatically initiated and the url is filled in by other programs, so I may not be able to use site transcoding

**Comment by QWXL** [comment]
> I think you can just encode your url?
> 
> https://www.urlencoder.org/

And using ISO encoding is outdated, fetch still works on the latest version of the server, so I think it deserves to go a step further and use the more widespread and advanced UTF-8

**Comment by Toshimichi0915** [comment]
I mean, URL doesn't support full UTF-8. For example, you can't contain "<" in your URL query.

According to RFC 1738            Uniform Resource Locators (URL)        December 1994:

>  URLs are written only with the graphic printable characters of the
   US-ASCII coded character set. The octets 80-FF hexadecimal are not
   used in US-ASCII, and the octets 00-1F and 7F hexadecimal represent
   control characters; these must be encoded.

I can't support UTF-8 encoding even if I wanted to. If I encode the entire URL string, "/" will be converted to "%2F". This means for example if I encoded "https://example.com", the whole string will be converted to "https%3A%2F%2Fexample.com", which is an invalid URL. If you really want to use UTF-8 characters in your server, you have to fix your plugin, or you can send me the URL to the plugin source code and let me modify the code.

**Comment by Toshimichi0915** [comment]
Well, I _might_ fix the issue, but it will take a while.

**Comment by QWXL** [comment]
> Well, I _might_ fix the issue, but it will take a while.

Thank you very much. And please, if possible, as soon as possible
