### ISSUE TITLE
Please allow me to interrupt.

### ISSUE THREAD

**Issue by QWXL** [Toshimichi0915/fetch#6]
May I ask how far along you are in your restoration? Please pardon my anxiety, I really, really need this extension to support Chinese, it's very important to me!
I'm not particularly good at Java, and I'm not sure how much effort it might take to fix it, but my players and I really need this extension to allow Chinese, and if you can fix it for them as soon as possible, hundreds of us would be very grateful to you.

**Comment by Toshimichi0915** [comment]
I'll try if I can fix that in a week.

**Comment by QWXL** [comment]
> I'll try if I can fix that in a week.

Thanks u very much!!

**Comment by QWXL** [comment]
> I'll try if I can fix that in a week.

To facilitate your debugging, I can provide a few Chinese words for you, these words have strict correlation and order, if the words can be submitted normally, then the plugin is running normally

"中国" "中文" "测试"
These three Chinese words mean "China", "Chinese" and "test", and I've used English quotation marks to label them.
These use UTF-8

**Comment by Toshimichi0915** [comment]
https://github.com/Toshimichi0915/fetch/tree/non-ascii

can you test new version before releasing it to the public?

[fetch-1.0.3.zip](https://github.com/Toshimichi0915/fetch/files/12839933/fetch-1.0.3.zip)

**Comment by QWXL** [comment]
> https://github.com/Toshimichi0915/fetch/tree/non-ascii
> 
> can you test new version before releasing it to the public?
> 
> [fetch-1.0.3.zip](https://github.com/Toshimichi0915/fetch/files/12839933/fetch-1.0.3.zip)

I tested it and it works as expected

**Comment by Toshimichi0915** [comment]
Sounds good. I will be releasing this version to the public in a few days hopefully.

**Comment by QWXL** [comment]
> Sounds good. I will be releasing this version to the public in a few days hopefully.

Yes, thank you very much.

**Comment by Toshimichi0915** [comment]
https://api.extendedclip.com/expansions/fetch/
